const ERROR_BAD_REQUEST = 400;
const NOT_FOUND_ERROR = 404;
const ERROR_CODE = 500;
const UNAUTHORIZED_ERROR = 401;
module.exports = {
  ERROR_BAD_REQUEST,
  NOT_FOUND_ERROR,
  ERROR_CODE,
  UNAUTHORIZED_ERROR,
};
